---
title: "ash-microclimate-data-cleaning"
author: "Deidre Jaeger"
date: "10/12/2018"
output: html_document
---

```{r install-packages-library results='hide', echo = FALSE}
# install.packages("dplyr")
# install.packages("lubridate")
library(dplyr) # mutate function
library(lubridate) # as.POSIX function
options(stringsAsFactors = FALSE) # makes dates strings
```

```{r import-100e-treatment-data, echo = FALSE}
# treatment 100e before removal
treatment_100e_before <- read.csv("data/SN 20439121 2018-09-20 00_06_33 -0600.csv", skip = 1, header = TRUE, col.names = c("date_time", "tempF", "sensor_sn", "sensor_name", "ash_removal", "blank1"))

treatment_100e_before$blank1 <- NULL
treatment_100e_before$sensor_sn <- rep(20439121)
treatment_100e_before$sensor_name <- rep("treatment_tree_100e")
treatment_100e_before$ash_removal <- rep("before_removal")

head(treatment_100e_before)

str(treatment_100e_before)

#############

# treatment 100e after removal
treatment_100e_after <- read.csv("data/SN 20439121 2018-09-26 10_27_52 -0600.csv", skip = 1, header = TRUE, col.names = c("date_time", "tempF", "sensor_sn", "sensor_name", "ash_removal", "blank1"))

treatment_100e_after$blank1 <- NULL
treatment_100e_after$sensor_sn <- rep(20439121)
treatment_100e_after$sensor_name <- rep("treatment_tree_100e")
treatment_100e_after$ash_removal <- rep("after_removal")

head(treatment_100e_after)

# combines before and after treatments into one datafrome
treatment_100e_clean <- rbind(treatment_100e_before, treatment_100e_after)

str(treatment_100e_clean)  

# formats date 
treatment_100e_clean <- treatment_100e_clean %>% mutate(date_time = ymd_hms(date_time))

treatment_100e_clean %>% write.csv(file = "data/treatment_100e_clean.csv")

str(treatment_100e_clean)

head(treatment_100e_clean)
```

```{r import-101w-treatment-data, echo = FALSE}
# treatment 101w before removal
treatment_101w_before <- read.csv("data/SN 20439119 2018-09-20 00_07_03 -0600.csv", skip = 1, header = TRUE, col.names = c("date_time", "tempF", "sensor_sn", "sensor_name", "ash_removal", "blank1"))

treatment_101w_before$blank1 <- NULL
treatment_101w_before$sensor_sn <- rep(20439119)
treatment_101w_before$sensor_name <- rep("treatment_tree_101w")
treatment_101w_before$ash_removal <- rep("before_removal")

head(treatment_101w_before)

str(treatment_101w_before)

#############

# treatment 101w after removal
treatment_101w_after <- read.csv("data/SN 20439119 2018-09-26 10_22_57 -0600.csv", skip = 1, header = TRUE, col.names = c("date_time", "tempF", "sensor_sn", "sensor_name", "ash_removal", "blank1"))

treatment_101w_after$blank1 <- NULL
treatment_101w_after$sensor_sn <- rep(20439119)
treatment_101w_after$sensor_name <- rep("treatment_tree_101w")
treatment_101w_after$ash_removal <- rep("after_removal")

head(treatment_101w_after)

treatment_101w_clean <- rbind(treatment_101w_before, treatment_101w_after)

str(treatment_101w_clean)

treatment_101w_clean <- treatment_101w_clean %>% mutate(date_time = ymd_hms(date_time))

treatment_101w_clean %>% write.csv(file = "data/treatment_101w_clean.csv")

str(treatment_101w_clean)

head(treatment_101w_clean)
```

```{r import-103-control-data, echo = FALSE}
control_103_data <- read.csv("data/SN 20397886 2018-09-26 10_27_32 -0600.csv", skip = 1, header = TRUE, col.names = c("date_time", "tempF", "sensor_sn", "sensor_name", "ash_removal", "blank1"))

control_103_data$blank1 <- NULL
control_103_data$sensor_sn <- rep(20397886)
control_103_data$sensor_name <- rep("control_tree_103")

head(control_103_data)

str(control_103_data)

# format date and time
control_103_data <- control_103_data %>% mutate(date_time = ymd_hms(date_time))

control_103_data_before <- control_103_data %>% filter(date_time <= ymd_hms("2018-09-20 00:03:59")) %>% mutate(ash_removal = "before_removal") 

control_103_data_during <- control_103_data %>% filter((date_time >= ymd_hms("2018-09-20 00:04:00")) & (date_time <= ymd_hms("2018-09-20 12:20:59"))) %>% mutate(ash_removal = "during_removal")

control_103_data_after <- control_103_data %>% filter(date_time >= ymd_hms("2018-09-20 12:21:00")) %>% mutate(ash_removal = "after_removal")

# combine data
control_103_data_clean <- rbind(control_103_data_before, control_103_data_during, control_103_data_after)

control_103_data_clean %>% write.csv(file = "data/control_103_data_clean.csv")

head(control_103_data_clean)

str(control_103_data_clean)

# check data
unique(control_103_data_clean$ash_removal)

nrow(control_103_data) == nrow(control_103_data_clean)
```

```{r import-sun-control-data, echo = FALSE}
control_sun_data <- read.csv("data/SN 20439118 2018-09-26 10_29_52 -0600.csv", skip = 1, header = TRUE, col.names = c("date_time", "tempF", "sensor_sn", "sensor_name", "ash_removal", "blank1"))

control_sun_data$blank1 <- NULL
control_sun_data$sensor_sn <- rep(20439118)
control_sun_data$sensor_name <- rep("control_sun")

head(control_sun_data)

str(control_sun_data)

# format date and time
control_sun_data <- control_sun_data %>% mutate(date_time = ymd_hms(date_time))

control_sun_data_before <- control_sun_data %>% filter(date_time <= ymd_hms("2018-09-20 00:03:59")) %>% mutate(ash_removal = "before_removal") 

control_sun_data_during <- control_sun_data %>% filter((date_time >= ymd_hms("2018-09-20 00:04:00")) & (date_time <= ymd_hms("2018-09-20 12:20:59"))) %>% mutate(ash_removal = "during_removal")

control_sun_data_after <- control_sun_data %>% filter(date_time >= ymd_hms("2018-09-20 12:21:00")) %>% mutate(ash_removal = "after_removal")

# combine data
control_sun_data_clean <- rbind(control_sun_data_before, control_sun_data_during, control_sun_data_after)

head(control_sun_data_clean)

str(control_sun_data_clean)

control_sun_data_clean %>% write.csv(file = "data/control_sun_data_clean.csv")

# check data
unique(control_sun_data_clean$ash_removal)

nrow(control_sun_data) == nrow(control_sun_data_clean)
```

```{r combine-data, echo = FALSE}
# remove 'during' dataframe
all_data <- rbind(treatment_100e_clean, treatment_101w_clean, control_103_data_clean, control_sun_data_clean)
```

```{r format-date-time, echo = FALSE}
all_data <- all_data %>% mutate(sensor_sn = as.factor(sensor_sn), sensor_name = as.factor(sensor_name), ash_removal = as.factor(ash_removal))

head(all_data)

str(all_data)
```

```{r set-factors, echo = FALSE}
# check for NA in data
all_data %>% filter(is.na(tempF))

# remove rows with NA (! = not equal to)
all_data <- all_data %>% filter(!is.na(tempF))
```

```{r export-csv, echo = FALSE}
all_data %>% write.csv(file = "data/ash-microclimate-data2018.csv")
```



